export const qualityDropdown = [
    { label: "All", value: "" },
    { label: "480p", value: "480p" },
    { label: "720p", value: "720p" },
    { label: "1080p", value: "1080p" },
    { label: "2160p", value: "2160p" },
    { label: "3D", value: "3D" },
];

export const genreDropdown = [
    { label: "All", value: "" },
    { label: "Action", value: "Action" },
    { label: "Adventure", value: "Adventure" },
    { label: "Animation", value: "Animation" },
    { label: "Biography", value: "Biography" },
    { label: "Comedy", value: "Comedy" },
    { label: "Crime", value: "Crime" },
    { label: "Documentary", value: "Documentary" },
    { label: "Drama", value: "Drama" },
    { label: "Family", value: "Family" },
    { label: "Fantasy", value: "Fantasy" },
    { label: "Film-Noir", value: "Film-Noir" },
    { label: "Game-Show", value: "Game-Show" },
    { label: "History", value: "History" },
    { label: "Horror", value: "Horror" },
    { label: "Music", value: "Music" },
    { label: "Musical", value: "Musical" },
    { label: "Mystery", value: "Mystery" },
    { label: "News", value: "News" },
    { label: "Reality-TV", value: "Reality-TV" },
    { label: "Romance", value: "Romance" },
    { label: "Sci-Fi", value: "Sci-Fi" },
    { label: "Sport", value: "Sport" },
    { label: "Talk-Show", value: "Talk-Show" },
    { label: "Thriller", value: "Thriller" },
    { label: "War", value: "War" },
    { label: "Western", value: "Western" },
];

export const ratingDropdown = [
    { label: "All", value: "" },
    { label: "9+", value: "9+" },
    { label: "8+", value: "8+" },
    { label: "7+", value: "7+" },
    { label: "6+", value: "6+" },
    { label: "5+", value: "5+" },
    { label: "4+", value: "4+" },
    { label: "3+", value: "3+" },
    { label: "2+", value: "2+" },
    { label: "1+", value: "1+" },
];

export const yearDropdown = [
    { label: "All", value: "" },
    { label: "2023", value: "2023" },
    { label: "2022", value: "2022" },
    { label: "2020 - now", value: "2020 - now" },
    { label: "2010 - now", value: "2010 - now" },
    { label: "2010 - 2019", value: "2010 - 2019" },
    { label: "2000 - 2009", value: "2000 - 2009" },
    { label: "1990 - 1999", value: "1990 - 1999" },
    { label: "1980 - 1989", value: "1980 - 1989" },
    { label: "1970 - 1979", value: "1970 - 1979" },
    { label: "1950 - 1969", value: "1950 - 1969" },
    { label: "1900 - 1949", value: "1950 - 1969" },
];

export const languageDropdown = [
    { label: "All", value: "" },
    { label: "English", value: "English" },
    { label: "Foreign", value: "Foreign" },
    { label: "French", value: "French" },
    { label: "Japanese", value: "Japanese" },
    { label: "Spanish", value: "Spanish" },
    { label: "Italian", value: "Italian" },
    { label: "Germen", value: "Germen" },
    { label: "Chinese", value: "Chinese" },
    { label: "Korean", value: "Korean" },
    { label: "Cantonese", value: "Cantonese" },
    { label: "Hindi", value: "Hindi" },
    { label: "Russian", value: "Russian" },
    { label: "Swedish", value: "Swedish" },
];

export const orderByDropdown = [
    { label: "Latest", value: "Latest" },
    { label: "Oldest", value: "Oldest" },
    { label: "Featured", value: "Featured" },
    { label: "Seeds", value: "Seeds" },
    { label: "Peers", value: "Peers" },
    { label: "Year", value: "Year" },
    { label: "IMDb Rating", value: "IMDb Rating" },
    { label: "CineFlix Likes", value: "CineFlix Likes" },
    { label: "RT Audience", value: "RT Audience" },
    { label: "Alphabetical", value: "Alphabetical" },
    { label: "Downloads", value: "Downloads" },
];